# Generated by Django 5.0.3 on 2024-03-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classs',
            name='batch',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='phno',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phno',
            field=models.IntegerField(unique=True),
        ),
    ]
