# Generated by Django 5.0.3 on 2024-03-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_student_phno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='classs',
            new_name='class_sec',
        ),
    ]
