# Generated by Django 5.0.3 on 2024-03-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_classs_batch_alter_student_phno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phno',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
