# Generated by Django 5.0.3 on 2024-03-20 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_rename_classs_student_class_sec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_sec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.classs'),
        ),
    ]
